version: '3'

services:
  hosting:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "21:21"       # FTP
      - "20:20"       # FTP data transfer
      - "21100-21110:21100-21110"  # Passive ports
    volumes:
      # - .:/opt/app
      - ./.docker/www:/var/www
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/dnsmasq/users.hosts.dat:/etc/dnsmasq.d/users.hosts.dat
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/http.d:/etc/nginx/http.d
      - ./.docker/vsftpd/virtual_users:/etc/vsftpd/virtual_users
      - ./.docker/vsftpd/user_confs:/etc/vsftpd/vusers
    depends_on:
      - mysql
      - redis

  worker:
    build: .
    depends_on:
      - redis
      - mysql
    volumes:
      - .:/opt/app
      - ./.docker/www:/var/www
    command: php /opt/app/app/worker/HostingWorker.php

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: upcehosting
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass

  redis:  
    image: redis:7
    restart: always
